### PR TITLE
Adding new images 2

### PR DESCRIPTION
**Pull request by slysnivy**
Adding images for key presses. The arrows can be used for direction as well. Currently the images are 64 x 64 and 312 x 64 for the space bar

### CODE REVIEW

**Comment by slysnivy** [comment]
This is apart of #395, but won't resolve it since I need to implement a system for it in game

**Comment by shoc71** [comment]
question, where do you get/create these images?

**Comment by slysnivy** [comment]
> question, where do you get/create these images?

I made them in paint

**Comment by shoc71** [comment]
oh nice

**Pull request merged**
