### PR TITLE
Adding new levels 15

### PR DESCRIPTION
**Pull request by shoc71**
- 2 new levels added
- 007_nightmode might seem weird but the self.draw and self.platforms positions were flipped

### CODE REVIEW

**Review by slysnivy — APPROVED** [review]
Looks good

**Comment by slysnivy** [comment]
> * 007_nightmode might seem weird but the self.draw and self.platforms positions were flipped
Could you elaborate on what this does because I'm pretty sure it won't make a difference if you're trying to mess with the layering.

**Comment by shoc71** [comment]
> > * 007_nightmode might seem weird but the self.draw and self.platforms positions were flipped
> >   Could you elaborate on what this does because I'm pretty sure it won't make a difference if you're trying to mess with the layering.

It's to mess with the layering of the objects being displayed. Mainly for art reasons, wont affect any gameplay. The only reason this is done is to make a background.

**Comment by slysnivy** [comment]
Disregard what I said before because I thought the code would always render platforms no matter the order that the level data is imported.

**Pull request merged**
